version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    environment:
      - DATABASE_URL=mysql://root:123@mysql_db:3306/dbtasks?serverVersion=8.0&charset=utf8mb4
      - COMPOSER_ALLOW_SUPERUSER=1
    command: php-fpm

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf:ro
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: dbtasks
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - "./database/task_app_ddl.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
